name = "modern-med-clinic"
pages_build_output_dir = "."
compatibility_date = "2026-05-24"

[[kv_namespaces]]
binding = "REVIEWS_KV"
id = "57b52c32ccc3451c94ef320f7cbfce35"

[vars]
REVIEW_TO = "contact@modernmedclinic.ro"
MAIL_FROM = "Modern Med Clinic <contact@modernmedclinic.ro>"
ADMIN_PASSWORD = "modern2026"
